spring.application.name=courseregistarionsystem2
spring.datasource.url=jdbc:mysql://localhost:3306/courseregistrationsystem
spring.datasource.username=root
spring.datasource.password=Test@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true