spring.application.name=employeesystem
server.port = 8088

#MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/cacheapp
spring.datasource.username=root
spring.datasource.password=Test@1234

#JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#user roles
#role.admin=ADMIN
#role.user=USER
